#!/bin/bash

if [ "$1" == "--pt" ] || [ "$2" == "--pt" ] || [ "$3" == "--pt" ]; then
    language="pt"
fi

if [ "$1" == "--en" ] || [ "$2" == "--en" ] || [ "$3" == "--en" ]; then
    language="en"
fi


# Choice Package Manager | Npm | Yarn | Bun |------------------------------------------------------------------
if [ "$1" == "--npm" ] || [ "$2" == "--npm" ] || [ "$3" == "--npm" ]; then
    packageManager="npm"
fi

if [ "$1" == "--yarn" ] || [ "$2" == "--yarn" ] || [ "$3" == "--yarn" ]; then
    packageManager="yarn"
fi

if [ "$1" == "--bun" ] || [ "$2" == "--bun" ] || [ "$3" == "--bun" ]; then
    packageManager="bun"
fi
# Choice Channel |--------------------------------------------------------------------------------------------
if [ "$1" == "--development" ] || [ "$2" == "--development" ] || [ "$3" == "--development" ]; then
    channel="development"
fi

if [ "$1" == "--production" ] || [ "$2" == "--production" ] || [ "$3" == "--production" ]; then
    channel="production"
fi

if [ "$1" == "--test" ] || [ "$2" == "--test" ] || [ "$3" == "--test" ]; then
    channel="test"
fi
